### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7621/problem-set-5#2]
```yaml
answer-1: chr1
answer-2: chrY:15475619-19472504
answer-3: @cluster_36:UMI_AACAGA
answer-4: 2136
answer-5: ['GCGCCCGGCTGAAGATTATGTGCCCCGGAAA', ... ]
```
